on: [push]

name: runner-example

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: iterative/setup-cml@v1
    - name: train model
      run: |
          pip install -r requirements.txt
          python train.py  # generate plot.png#
          ls -l
      env:
          REPO_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
