on: [push]

name: runner-example

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
#    - uses: actions/setup-python@v4  # testing cml-gpu self hosting###
    - uses: iterative/setup-cml@v1   # not required in container###
    - name: train model
      run: |
          pip install -r requirements.txt
          python train.py  # generate plot.png#
          # Create CML report
          cat metrics.txt >> report.md
          # echo '![](./plot.png)' >> report.md
          cml comment create --publish report.md
      env:
          REPO_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
